name = "Simple Vanilla Overhaul"
author = "pajic"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "589b542b6d7085e86a2a8c24fc978a5780426f4e6cebc2378407378b8181aea9"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
datapack-folder = "resources/datapack/required"
