name = "Simple Vanilla Overhaul"
author = "pajic"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61fd69dad47fe2fe55da4b751fe6d2f7727613b7fd2cc96bb2d36f7e2d87f5b3"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
datapack-folder = "resources/datapack/required"
