name = "Simple Vanilla Overhaul"
author = "pajic"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fca6568251d31c67b4f2562c8e2f67f318e78ec1590ef8eeaca6b4ddbe62748b"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
datapack-folder = "resources/datapack/required"
